// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.EFCore;

#nullable disable

namespace KlinikRandevu.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20260511181849_parametreler")]
    partial class parametreler
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DoktorAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ServisNo")
                        .HasColumnType("int");

                    b.Property<int>("doktorNo")
                        .HasColumnType("int");

                    b.Property<long>("doktorTc")
                        .HasColumnType("bigint");

                    b.Property<int>("doktorUzKod")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<int>("tescilNO")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("doktorNo")
                        .IsUnique();

                    b.HasIndex("doktorTc")
                        .IsUnique();

                    b.ToTable("Doktorlar", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoktorAd = "HÜSEYİN AĞAC",
                            ServisNo = 1,
                            doktorNo = 1,
                            doktorTc = 11111111111L,
                            doktorUzKod = 1000,
                            isActive = true,
                            tescilNO = 10001
                        },
                        new
                        {
                            Id = 2,
                            DoktorAd = "AYŞE DEMİR",
                            ServisNo = 2,
                            doktorNo = 2,
                            doktorTc = 22222222222L,
                            doktorUzKod = 1100,
                            isActive = true,
                            tescilNO = 10002
                        },
                        new
                        {
                            Id = 3,
                            DoktorAd = "MEHMET YILMAZ",
                            ServisNo = 3,
                            doktorNo = 3,
                            doktorTc = 33333333333L,
                            doktorUzKod = 1300,
                            isActive = true,
                            tescilNO = 10003
                        });
                });

            modelBuilder.Entity("Entities.Models.DoktorCalismaPlani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("BaslangicSaati")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("BitisSaati")
                        .HasColumnType("time");

                    b.Property<int>("DoktorNo")
                        .HasColumnType("int");

                    b.Property<int>("GunAdi")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("PolNo")
                        .HasColumnType("int");

                    b.Property<int>("RandevuSuresiDk")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CalismaPlanlari", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaslangicSaati = new TimeSpan(0, 8, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 12, 0, 0, 0),
                            DoktorNo = 1,
                            GunAdi = 1,
                            IsActive = true,
                            PolNo = 1,
                            RandevuSuresiDk = 10
                        },
                        new
                        {
                            Id = 2,
                            BaslangicSaati = new TimeSpan(0, 8, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 12, 0, 0, 0),
                            DoktorNo = 1,
                            GunAdi = 3,
                            IsActive = true,
                            PolNo = 1,
                            RandevuSuresiDk = 10
                        },
                        new
                        {
                            Id = 3,
                            BaslangicSaati = new TimeSpan(0, 8, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 12, 0, 0, 0),
                            DoktorNo = 1,
                            GunAdi = 5,
                            IsActive = true,
                            PolNo = 1,
                            RandevuSuresiDk = 10
                        },
                        new
                        {
                            Id = 4,
                            BaslangicSaati = new TimeSpan(0, 9, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 17, 0, 0, 0),
                            DoktorNo = 2,
                            GunAdi = 2,
                            IsActive = true,
                            PolNo = 2,
                            RandevuSuresiDk = 15
                        },
                        new
                        {
                            Id = 5,
                            BaslangicSaati = new TimeSpan(0, 9, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 17, 0, 0, 0),
                            DoktorNo = 2,
                            GunAdi = 4,
                            IsActive = true,
                            PolNo = 2,
                            RandevuSuresiDk = 15
                        },
                        new
                        {
                            Id = 6,
                            BaslangicSaati = new TimeSpan(0, 10, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 16, 0, 0, 0),
                            DoktorNo = 3,
                            GunAdi = 1,
                            IsActive = true,
                            PolNo = 3,
                            RandevuSuresiDk = 20
                        },
                        new
                        {
                            Id = 7,
                            BaslangicSaati = new TimeSpan(0, 10, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 16, 0, 0, 0),
                            DoktorNo = 3,
                            GunAdi = 2,
                            IsActive = true,
                            PolNo = 3,
                            RandevuSuresiDk = 20
                        },
                        new
                        {
                            Id = 8,
                            BaslangicSaati = new TimeSpan(0, 10, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 16, 0, 0, 0),
                            DoktorNo = 3,
                            GunAdi = 3,
                            IsActive = true,
                            PolNo = 3,
                            RandevuSuresiDk = 20
                        },
                        new
                        {
                            Id = 9,
                            BaslangicSaati = new TimeSpan(0, 10, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 16, 0, 0, 0),
                            DoktorNo = 3,
                            GunAdi = 4,
                            IsActive = true,
                            PolNo = 3,
                            RandevuSuresiDk = 20
                        },
                        new
                        {
                            Id = 10,
                            BaslangicSaati = new TimeSpan(0, 10, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 16, 0, 0, 0),
                            DoktorNo = 3,
                            GunAdi = 5,
                            IsActive = true,
                            PolNo = 3,
                            RandevuSuresiDk = 20
                        });
                });

            modelBuilder.Entity("Entities.Models.MuayeneKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("BaslangicSaati")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("BitisSaati")
                        .IsRequired()
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoktorNo")
                        .HasColumnType("int");

                    b.Property<long>("HastaTc")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("MuayeneTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("PolNo")
                        .HasColumnType("int");

                    b.Property<int>("ProtocolNo")
                        .HasColumnType("int");

                    b.Property<int?>("RandevuId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MuayeneKayitlari", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BloodType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Protocol")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("TcKimlik")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "BURSA, Türkiye",
                            BirthDate = new DateTime(2001, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BloodType = 6,
                            CreatedAt = new DateTime(2026, 5, 11, 21, 18, 49, 263, DateTimeKind.Local).AddTicks(7738),
                            Gender = 2,
                            IsActive = true,
                            Name = "BATUHAN",
                            Phone = "5378102935",
                            Protocol = 20261,
                            Surname = "KÖSE",
                            TcKimlik = 11111111111L
                        });
                });

            modelBuilder.Entity("Entities.Models.Poliklinik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DoktorNo")
                        .HasColumnType("int");

                    b.Property<int?>("GunlukMaksRandevuSayisi")
                        .HasColumnType("int");

                    b.Property<int?>("KatNo")
                        .HasColumnType("int");

                    b.Property<int?>("MaxRandevuSuresi")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OdaNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("OnlineRandevuAktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PolNo")
                        .HasColumnType("int");

                    b.Property<int>("PolUzKod")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("PolNo")
                        .IsUnique();

                    b.ToTable("Poliklinikler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "İÇ Hastalıkları pol öğleden önce",
                            DoktorNo = 1,
                            GunlukMaksRandevuSayisi = 30,
                            KatNo = 1,
                            MaxRandevuSuresi = 10,
                            Name = "İÇ HASTALIKLARI HÜSEYİN AĞAC",
                            OdaNo = "Birinci kat",
                            OnlineRandevuAktif = true,
                            PolNo = 1,
                            PolUzKod = 1000,
                            Telefon = "1650",
                            isActive = true
                        });
                });

            modelBuilder.Entity("Entities.Models.Randevu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoktorNo")
                        .HasColumnType("int");

                    b.Property<long>("HastaTc")
                        .HasColumnType("bigint");

                    b.Property<string>("Notlar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PolNo")
                        .HasColumnType("int");

                    b.Property<int>("ProtocolNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("RandevuTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SureDakika")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoktorNo", "RandevuTarihi")
                        .IsUnique();

                    b.ToTable("Randevular", (string)null);
                });

            modelBuilder.Entity("Entities.Models.SistemParametresi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Deger1")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Deger2")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Deger3")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Deger4")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Deger5")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParametreAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ParametreAdi")
                        .IsUnique();

                    b.ToTable("parametreler");
                });
#pragma warning restore 612, 618
        }
    }
}
